name: 'Publish'


on:
  workflow_dispatch:

  release:
    types: [created]
    tags: ["v*.*.*"]


concurrency:
  group: ci-${{ github.repository }}
  cancel-in-progress: true


env:
  IMAGE_NAME: 'discord-bot'


jobs:
  build:
    name: 'Building Docker Image'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v5.0.0

    - name: 'Get tag'
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v3

    - name: Build Docker
      run: |
        docker build -f ./Dockerfile . -t ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}

    - name: 'Save Docker Image'
      run: |
        docker save -o ${{ env.IMAGE_NAME }}.tar ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.IMAGE_NAME }}
        path: ${{ env.IMAGE_NAME }}.tar
        retention-days: 1



  publish:
    name: 'Publish Docker Image to Docker Hub'
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: 'Download artifact'
      uses: actions/download-artifact@v5
      with:
        name: ${{ env.IMAGE_NAME }}

    - name: 'Get tag'
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v3

    - name: 'Login to Docker Hub'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Load & Push Docker Image
      run: |
        docker load -i ${{ env.IMAGE_NAME }}.tar

    - name: 'Add Docker Image Tags'
      run: |
        docker tag ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} ${{ secrets.DOCKERHUB_USERNAME  }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
        docker tag ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} ${{ secrets.DOCKERHUB_USERNAME  }}/${{ env.IMAGE_NAME }}:latest

    - name: 'Push Docker Image to GitHub Container Registry'
      run: |
        docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME  }}/${{ env.IMAGE_NAME }}
